(cl:in-package moveit_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          ORIENTATION-VAL
          ORIENTATION
          LINK_NAME-VAL
          LINK_NAME
          ABSOLUTE_X_AXIS_TOLERANCE-VAL
          ABSOLUTE_X_AXIS_TOLERANCE
          ABSOLUTE_Y_AXIS_TOLERANCE-VAL
          ABSOLUTE_Y_AXIS_TOLERANCE
          ABSOLUTE_Z_AXIS_TOLERANCE-VAL
          ABSOLUTE_Z_AXIS_TOLERANCE
          PARAMETERIZATION-VAL
          PARAMETERIZATION
          WEIGHT-VAL
          WEIGHT
))