(cl:in-package moveit_msgs-msg)
(cl:export '(GROUP_NAME-VAL
          GROUP_NAME
          ATTACHED_OBJECT_NAME-VAL
          ATTACHED_OBJECT_NAME
          PLACE_LOCATIONS-VAL
          PLACE_LOCATIONS
          PLACE_EEF-VAL
          PLACE_EEF
          SUPPORT_SURFACE_NAME-VAL
          SUPPORT_SURFACE_NAME
          ALLOW_GRIPPER_SUPPORT_COLLISION-VAL
          ALLOW_GRIPPER_SUPPORT_COLLISION
          PATH_CONSTRAINTS-VAL
          PATH_CONSTRAINTS
          PLANNER_ID-VAL
          PLANNER_ID
          ALLOWED_TOUCH_OBJECTS-VAL
          ALLOWED_TOUCH_OBJECTS
          ALLOWED_PLANNING_TIME-VAL
          ALLOWED_PLANNING_TIME
          PLANNING_OPTIONS-VAL
          PLANNING_OPTIONS
))