(cl:in-package moveit_msgs-msg)
(cl:export '(ERROR_CODE-VAL
          ERROR_CODE
          TRAJECTORY_START-VAL
          TRAJECTORY_START
          TRAJECTORY_STAGES-VAL
          TRAJECTORY_STAGES
          TRAJECTORY_DESCRIPTIONS-VAL
          TRAJECTORY_DESCRIPTIONS
          PLACE_LOCATION-VAL
          PLACE_LOCATION
          PLANNING_TIME-VAL
          PLANNING_TIME
))