(cl:in-package moveit_msgs-msg)
(cl:export '(JOINT_NAME-VAL
          JOINT_NAME
          HAS_POSITION_LIMITS-VAL
          HAS_POSITION_LIMITS
          MIN_POSITION-VAL
          MIN_POSITION
          MAX_POSITION-VAL
          MAX_POSITION
          HAS_VELOCITY_LIMITS-VAL
          HAS_VELOCITY_LIMITS
          MAX_VELOCITY-VAL
          MAX_VELOCITY
          HAS_ACCELERATION_LIMITS-VAL
          HAS_ACCELERATION_LIMITS
          MAX_ACCELERATION-VAL
          MAX_ACCELERATION
))