(cl:in-package moveit_msgs-msg)
(cl:export '(TARGET_NAME-VAL
          TARGET_NAME
          GROUP_NAME-VAL
          GROUP_NAME
          END_EFFECTOR-VAL
          END_EFFECTOR
          POSSIBLE_GRASPS-VAL
          POSSIBLE_GRASPS
          SUPPORT_SURFACE_NAME-VAL
          SUPPORT_SURFACE_NAME
          ALLOW_GRIPPER_SUPPORT_COLLISION-VAL
          ALLOW_GRIPPER_SUPPORT_COLLISION
          ATTACHED_OBJECT_TOUCH_LINKS-VAL
          ATTACHED_OBJECT_TOUCH_LINKS
          MINIMIZE_OBJECT_DISTANCE-VAL
          MINIMIZE_OBJECT_DISTANCE
          PATH_CONSTRAINTS-VAL
          PATH_CONSTRAINTS
          PLANNER_ID-VAL
          PLANNER_ID
          ALLOWED_TOUCH_OBJECTS-VAL
          ALLOWED_TOUCH_OBJECTS
          ALLOWED_PLANNING_TIME-VAL
          ALLOWED_PLANNING_TIME
          PLANNING_OPTIONS-VAL
          PLANNING_OPTIONS
))