(cl:in-package moveit_msgs-srv)
(cl:export '(DRIFT_X_TRANSLATION-VAL
          DRIFT_X_TRANSLATION
          DRIFT_Y_TRANSLATION-VAL
          DRIFT_Y_TRANSLATION
          DRIFT_Z_TRANSLATION-VAL
          DRIFT_Z_TRANSLATION
          DRIFT_X_ROTATION-VAL
          DRIFT_X_ROTATION
          DRIFT_Y_ROTATION-VAL
          DRIFT_Y_ROTATION
          DRIFT_Z_ROTATION-VAL
          DRIFT_Z_ROTATION
          TRANSFORM_JOG_FRAME_TO_DRIFT_FRAME-VAL
          TRANSFORM_JOG_FRAME_TO_DRIFT_FRAME
          SUCCESS-VAL
          SUCCESS
))