(cl:in-package moveit_msgs-srv)
(cl:export '(CONTROL_X_TRANSLATION-VAL
          CONTROL_X_TRANSLATION
          CONTROL_Y_TRANSLATION-VAL
          CONTROL_Y_TRANSLATION
          CONTROL_Z_TRANSLATION-VAL
          CONTROL_Z_TRANSLATION
          CONTROL_X_ROTATION-VAL
          CONTROL_X_ROTATION
          CONTROL_Y_ROTATION-VAL
          CONTROL_Y_ROTATION
          CONTROL_Z_ROTATION-VAL
          CONTROL_Z_ROTATION
          SUCCESS-VAL
          SUCCESS
))