// Generated by gencpp from file moveit_msgs/ApplyPlanningScene.msg
// DO NOT EDIT!


#ifndef MOVEIT_MSGS_MESSAGE_APPLYPLANNINGSCENE_H
#define MOVEIT_MSGS_MESSAGE_APPLYPLANNINGSCENE_H

#include <ros/service_traits.h>


#include <moveit_msgs/ApplyPlanningSceneRequest.h>
#include <moveit_msgs/ApplyPlanningSceneResponse.h>


namespace moveit_msgs
{

struct ApplyPlanningScene
{

typedef ApplyPlanningSceneRequest Request;
typedef ApplyPlanningSceneResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ApplyPlanningScene
} // namespace moveit_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::moveit_msgs::ApplyPlanningScene > {
  static const char* value()
  {
    return "d4d1599e0b6f71a6a8a10cb34780619c";
  }

  static const char* value(const ::moveit_msgs::ApplyPlanningScene&) { return value(); }
};

template<>
struct DataType< ::moveit_msgs::ApplyPlanningScene > {
  static const char* value()
  {
    return "moveit_msgs/ApplyPlanningScene";
  }

  static const char* value(const ::moveit_msgs::ApplyPlanningScene&) { return value(); }
};


// service_traits::MD5Sum< ::moveit_msgs::ApplyPlanningSceneRequest> should match
// service_traits::MD5Sum< ::moveit_msgs::ApplyPlanningScene >
template<>
struct MD5Sum< ::moveit_msgs::ApplyPlanningSceneRequest>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_msgs::ApplyPlanningScene >::value();
  }
  static const char* value(const ::moveit_msgs::ApplyPlanningSceneRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_msgs::ApplyPlanningSceneRequest> should match
// service_traits::DataType< ::moveit_msgs::ApplyPlanningScene >
template<>
struct DataType< ::moveit_msgs::ApplyPlanningSceneRequest>
{
  static const char* value()
  {
    return DataType< ::moveit_msgs::ApplyPlanningScene >::value();
  }
  static const char* value(const ::moveit_msgs::ApplyPlanningSceneRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::moveit_msgs::ApplyPlanningSceneResponse> should match
// service_traits::MD5Sum< ::moveit_msgs::ApplyPlanningScene >
template<>
struct MD5Sum< ::moveit_msgs::ApplyPlanningSceneResponse>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_msgs::ApplyPlanningScene >::value();
  }
  static const char* value(const ::moveit_msgs::ApplyPlanningSceneResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_msgs::ApplyPlanningSceneResponse> should match
// service_traits::DataType< ::moveit_msgs::ApplyPlanningScene >
template<>
struct DataType< ::moveit_msgs::ApplyPlanningSceneResponse>
{
  static const char* value()
  {
    return DataType< ::moveit_msgs::ApplyPlanningScene >::value();
  }
  static const char* value(const ::moveit_msgs::ApplyPlanningSceneResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEIT_MSGS_MESSAGE_APPLYPLANNINGSCENE_H
